name: Java CI with Maven

on:

  pull_request:

    branches:

      - main

jobs:
  ciworkpr:
  build:

    runs-on: ubuntu-latest

    permissions:

      contents: read

      packages: write

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 17

      uses: actions/setup-java@v3

      with:

        java-version: '17'

        distribution: 'adopt'

        cache: maven

    - name: Build with Maven

      run: "mvn -B package --file ./demo/pom.xml && mkdir artifacts && cp target/*.jar artifacts && cd artifacts && ls"

    - name: Build and Test
      run: "mvn clean install -X"


