name: Java CI with Maven

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: app test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17

        uses: actions/setup-java@v2

        with:
          java-version: "17"

          distribution: "temurin"

          cache: maven

      - name: Build & Test with Maven
        run: mvn clean install -DskipTests
        working-directory: demo

      - name: Package with Maven
        run: mvn -B package --file pom.xml -DskipTests
        working-directory: demo
